"""The ESP32-embedded SPA must stay in sync with web/index.html.

The ESP32 serves the shared web UI (web/index.html) at GET /app by embedding it as a C++ string in
firmware/lib/proxy/WebSpa.h, generated by web/gen_spa_header.py. This test runs the generator in
--check mode so the embedded copy can never drift from the source — edit web/index.html, regenerate.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "web" / "gen_spa_header.py"


def test_generator_exists() -> None:
    assert GEN.is_file(), f"the SPA header generator is missing: {GEN}"


def test_spa_header_in_sync() -> None:
    result = subprocess.run(
        [sys.executable, str(GEN), "--check"],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "firmware/lib/proxy/WebSpa.h has drifted from web/index.html — run "
        "`python web/gen_spa_header.py`.\n" + result.stdout + result.stderr
    )
