"""The ESP32-embedded SPA must stay in sync with web/index.html.

The ESP32 serves the shared web UI (web/index.html) at GET /app by embedding it as a C++ string in
firmware/lib/proxy/WebSpa.h, generated by web/gen_spa_header.py. This test runs the generator in
--check mode so the embedded copy can never drift from the source — edit web/index.html, regenerate.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "web" / "gen_spa_header.py"
SPA = ROOT / "web" / "index.html"


def test_generator_exists() -> None:
    assert GEN.is_file(), f"the SPA header generator is missing: {GEN}"


def test_untrusted_names_are_escaped() -> None:
    """Guard the DOM-XSS fix (2026-07-05): a BLE-advertised device name is attacker-controlled and
    the SPA serves same-origin with the board's HTTP API, so any `innerHTML` interpolation of `d.name`
    or a log message MUST go through `esc()`. This catches a future edit that pipes an untrusted value
    into innerHTML raw. (Deliberately narrow: it only checks the two known untrusted sinks.)"""
    html = SPA.read_text(encoding="utf-8")
    assert re.search(r"const esc\s*=", html), "the esc() HTML-escaper is gone from the SPA"
    # every innerHTML line that interpolates d.name / a log message must wrap it in esc(...)
    for ln in html.splitlines():
        if "innerHTML" not in ln:
            continue
        for token in ("${d.name}", "${m}", "${d.rssi}"):
            assert token not in ln, (
                f"unescaped untrusted value {token} in an innerHTML sink — wrap it in esc():\n  {ln.strip()}"
            )


def test_spa_header_in_sync() -> None:
    result = subprocess.run(
        [sys.executable, str(GEN), "--check"],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "firmware/lib/proxy/WebSpa.h has drifted from web/index.html — run "
        "`python web/gen_spa_header.py`.\n" + result.stdout + result.stderr
    )
