#pragma once
// GENERATED by code/scripts/gen_bridge.py from ui-schema/bridge.json — DO NOT EDIT.
// Golden byte vectors (hex) for the Bridge packets; test_bridge builds each struct with the
// schema's sample values and asserts Proto.h pack() == these bytes, locking Proto.h to the
// schema (so a Proto.h offset change without a schema update fails CI).
namespace bridge_golden {
inline constexpr const char* Status = "0115bffebffebffef92ad204960040e20100e110";
inline constexpr const char* Config = "0105d2049600535243460000000000000000000000000000004f55544e000000000000000000000000000000";
inline constexpr const char* Buttons = "01012a2a2a2a2a2a";
inline constexpr const char* RecState = "01012a0040e2010040e20100";
inline constexpr const char* CalState = "010100e110e11096002a2a2a2a2a2a01";
inline constexpr const char* WkState = "0115bffe2a2ae110bffee110bffe00000000";
inline constexpr const char* Curve = "0102e110d204e110d204";
inline constexpr const char* ScanList = "01024e414d45000000000000000000000000000000f9054e414d45000000000000000000000000000000f905";
}  // namespace bridge_golden
