#pragma once
// LvglUi — the LVGL v9 implementation of the head-unit UI (CYD 240x320 + S3-Touch 172x320).
//
// Replaces the hand-rolled LcdCanvas renderer ON DEVICE (the pure renderer stays host-tested and
// drives nothing here). Reuses the same view-model (LcdViews, built by main's buildLcdViews) and
// the same UiAction vocabulary, so main.cpp's data + action plumbing is unchanged: main pushes
// fresh views in, drains widget-emitted UiActions out.
//
// Styling follows the locked HTML design tokens (design/sb20-lcd-*.html): bg #0f1320, cards
// #1a2030 radius 12, fg #e8ecf4, muted #8b93a7, accent #3b82f6, ok #22c55e — with Inter baked at
// 12/16/20sb/28sb/64sb (src/ui/fonts, generated by lv_font_conv from design/fonts/inter).
#if defined(USE_LVGL) && USE_LVGL

#include <cstdint>

#include "LcdUi.h"  // LcdViews + UiAction + LcdScreen (the shared view-model/action types)

namespace sb20proxy {

struct LvglDriverHooks {
    // Blocking blit of an RGB565 area to the panel (the seam's setWindow + writePixels).
    void (*flushArea)(int x1, int y1, int x2, int y2, const uint16_t* px);
    // Current touch state: true while pressed, with panel coords (calibrated).
    bool (*readTouch)(int& x, int& y);
};

void lvglUiInit(const LvglDriverHooks& hooks, int hor, int ver);
void lvglUiTick();                                    // pump lv timers (call every ~5-20 ms)
void lvglUiUpdate(const LcdViews& v);                 // refresh the active screen's data
bool lvglUiPollAction(UiAction& out);                 // widget events -> UiActions
LcdScreen lvglUiCurrentScreen();
bool lvglUiRideDetails();                             // Ride IN/OUT pop-down open?
void lvglUiShowScreen(LcdScreen s);

// Touch-calibration ritual rendering (logic stays in main's touchCalTick):
void lvglUiCalShow(int step, int done, int testX, int testY);  // step<0 hides the cal screen

// SCREEN serial dump: tee the next full refresh's flushes out as <AREA ...> blocks.
void lvglUiScreenDumpBegin();
bool lvglUiScreenDumpActive();

}  // namespace sb20proxy
#endif  // USE_LVGL
