#requires -Version 7
<#
.SYNOPSIS
  (Re)generate firmware/ota_secret.h from Infisical — the vault is the source of truth; the header is a
  gitignored build artifact. Retires the hand-maintained ota_secret.h.

.DESCRIPTION
  Chain: secrets-get.ps1 (reads the read-only build identity from Windows Credential Manager) →
  universal-auth login → GET /api/v3/secrets/raw/OTA_PASSWORD → write firmware/ota_secret.h
  (`#pragma once` + `#define OTA_PASSWORD "…"`). The firmware compile (`WifiLink.cpp` `__has_include`)
  and flash.ps1 (espota `-a`) then consume the header unchanged.

  Run it before a build/flash to refresh from the vault. To rotate: change the secret in Infisical,
  re-run this, reflash. Prereq: secrets-pull.ps1 has stored the identity in Credential Manager, and the
  build machine can reach the Infisical host (LAN; use -HostUrl http://<ip>:8222 if mDNS won't resolve).

.PARAMETER Check
  Verify-only: compare the vault value to the existing header and write nothing. Exit 0 = in sync,
  1 = drift (missing / rotated). For doctor / CI.

.EXAMPLE
  ./secrets-sync-ota.ps1            # regenerate firmware/ota_secret.h from the vault
.EXAMPLE
  ./secrets-sync-ota.ps1 -Check     # is the local header in sync with the vault?
#>
[CmdletBinding()]
param(
    [string]$Identity   = 'sb20-power-proxy',
    [string]$SecretName = 'OTA_PASSWORD',
    [string]$HostUrl,                          # default: the identity's stored INFISICAL_HOST
    [string]$OutFile,                          # default: ../firmware/ota_secret.h
    [switch]$Check
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if (-not $OutFile) { $OutFile = Join-Path $PSScriptRoot '..\firmware\ota_secret.h' }

# 1. identity creds from Windows Credential Manager (captured into vars, never echoed)
$fields = @{}
foreach ($line in (& (Join-Path $PSScriptRoot 'secrets-get.ps1') -Identity $Identity -AsEnv)) {
    if ($line -match '^(INFISICAL_\w+)=(.*)$') { $fields[$Matches[1]] = $Matches[2] }
}
$infHost   = if ($HostUrl) { $HostUrl } else { $fields['INFISICAL_HOST'] }
$projectId = $fields['INFISICAL_PROJECT_ID']
$envName   = $fields['INFISICAL_ENV']
$clientId  = $fields['INFISICAL_CLIENT_ID']
$clientSec = $fields['INFISICAL_CLIENT_SECRET']
foreach ($n in 'infHost', 'projectId', 'envName', 'clientId', 'clientSec') {
    if (-not (Get-Variable $n -ValueOnly)) {
        throw "missing $n — run: tools\secrets-pull.ps1 -Identity $Identity"
    }
}

# 2. universal-auth login -> short-lived token
$login = Invoke-RestMethod -Method Post -Uri "$infHost/api/v1/auth/universal-auth/login" `
    -ContentType 'application/json' -Body (@{ clientId = $clientId; clientSecret = $clientSec } | ConvertTo-Json)
$token = $login.accessToken
if (-not $token) { throw "login returned no accessToken" }

# 3. read the secret
$enc = [uri]::EscapeDataString($SecretName)
$resp = Invoke-RestMethod -Method Get -Headers @{ Authorization = "Bearer $token" } `
    -Uri "$infHost/api/v3/secrets/raw/${enc}?workspaceId=$projectId&environment=$envName"
$val = $resp.secret.secretValue
if (-not $val) { throw "vault returned an empty $SecretName" }

# current value in the header, if any (for drift / change reporting — value never printed)
$current = $null
if (Test-Path $OutFile) {
    $mm = Select-String -Path $OutFile -Pattern '#define\s+OTA_PASSWORD\s+"([^"]*)"'
    if ($mm) { $current = $mm.Matches[0].Groups[1].Value }
}

if ($Check) {
    if ($current -eq $val) { Write-Host "in sync: $OutFile matches vault ($SecretName len $($val.Length))"; exit 0 }
    $how = if ($current) { 'differs from' } else { 'missing vs' }
    Write-Warning "DRIFT: header $how vault ($SecretName len $($val.Length)) — run tools\secrets-sync-ota.ps1"
    exit 1
}

# 4. write the gitignored build artifact
$content = @"
#pragma once
// GENERATED by tools/secrets-sync-ota.ps1 from Infisical ($Identity/$envName -> $SecretName).
// Do NOT edit or commit — the vault is the source of truth. Rotate in Infisical, re-run, reflash.
#define OTA_PASSWORD "$val"
"@
Set-Content -Path $OutFile -Value $content -Encoding utf8
$state = if ($current -eq $val) { 'unchanged' } elseif ($current) { 'UPDATED (rotated)' } else { 'created' }
Write-Host "wrote $OutFile — $state ($SecretName len $($val.Length))"
